// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBePY3UxQUWpTR01JvIYy_0GJgPfu-g4sE',
    appId: '1:497128473690:web:9002748ac6e8fd60ce0463',
    messagingSenderId: '497128473690',
    projectId: 'plantdoctor-61341',
    authDomain: 'plantdoctor-61341.firebaseapp.com',
    storageBucket: 'plantdoctor-61341.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbV13cW0CLy4D0Lzviv7hbk6x0KHif7VI',
    appId: '1:497128473690:android:d6e3fae757c86345ce0463',
    messagingSenderId: '497128473690',
    projectId: 'plantdoctor-61341',
    storageBucket: 'plantdoctor-61341.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf4cbqmqAwFMI9-bKOejeHUy3uj7CGzRk',
    appId: '1:497128473690:ios:e337812d4a28e000ce0463',
    messagingSenderId: '497128473690',
    projectId: 'plantdoctor-61341',
    storageBucket: 'plantdoctor-61341.appspot.com',
    iosBundleId: 'com.example.apptest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf4cbqmqAwFMI9-bKOejeHUy3uj7CGzRk',
    appId: '1:497128473690:ios:e337812d4a28e000ce0463',
    messagingSenderId: '497128473690',
    projectId: 'plantdoctor-61341',
    storageBucket: 'plantdoctor-61341.appspot.com',
    iosBundleId: 'com.example.apptest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBePY3UxQUWpTR01JvIYy_0GJgPfu-g4sE',
    appId: '1:497128473690:web:6316a4747151b146ce0463',
    messagingSenderId: '497128473690',
    projectId: 'plantdoctor-61341',
    authDomain: 'plantdoctor-61341.firebaseapp.com',
    storageBucket: 'plantdoctor-61341.appspot.com',
  );
}
